openapi: 3.0.3
info:
  title: Candor Api LOS Communication
  version: 0.17.0
  contact:
    name: Candor Api Specification
    url: https://github.com/candorfintech/Candor.Api.OpenAPI
externalDocs:
  description: Changelog
  url: https://github.com/candorfintech/Candor.Api.OpenAPI#changelog
tags:
- name: LOS
  description: LOS communication
  externalDocs:
    description: SwaggerUI
    url: https://candorfintech.github.io/Candor.Api.OpenAPI/?urls.primaryName=LOS
servers:
  - description: Development
    url: 'https://api-dev.candortechnology.com'
  - description: Staging
    url: 'https://api-stage.candortechnology.com'
  - description: Production
    url: 'https://api.candortechnology.com'

paths:
  /loan/subscribe:
    post:
      tags:
      - LOS
      summary: Register Callback (not currently implemented)
      description: |
        Subscribe an LOS callback Url to receive notifications when Candor results are available.

        **Note:** this is currently not implemented and only provided here for documentation of the object models.
      operationId: LosSubscribe
      security:
      - candor-api:
        - candorApi/write:los
      requestBody:
        required: true
        content:
          application/json:
            schema:
              title: Callback Registration
              type: object
              required:
              - callbackUrl
              properties:
                callbackUrl:
                  type: string
                  format: uri
                  description: The callback url
                auth:
                  type: object
                  title: Authentication
                  description: If authentication is required for the `callbackUrl`, this object represents the type of authentication to use as well as any needed parameters. Additional supported authentication types could be added as needed.
                  oneOf:
                  - type: object
                    title: Header Authentication
                    description: Static headers added to the callback request
                    required:
                    - type
                    - headers
                    properties:
                      type:
                        type: string
                        description: Constant value of `header`
                        default: header
                        enum:
                        - header
                      headers:
                        type: object
                        description: A collection of keys and values that'll be added to the headers of the callback request.
                        additionalProperties:
                          type: string
            examples:
              CallbackRegNoAuth:
                summary: Callback registration without Auth
                value:
                  callbackUrl: https://api.los.com/callback
              CallbackRegWithCustomHeaders:
                summary: Callback registration with Custom Header(s) Auth
                value:
                  callbackUrl: https://api.los.com/callback
                  auth:
                    type: header
                    headers:
                      x-api-key: abc-123
              CallbackRegWithApiKey:
                summary: Callback registration with Bearer Api Key
                value:
                  callbackUrl: https://api.los.com/callback
                  auth:
                    type: header
                    headers:
                      Authorization: Bearer secret-api-key
              CallbackRegWithBasic:
                summary: Callback registration with Basic Auth
                value:
                  callbackUrl: https://api.los.com/callback
                  auth:
                    type: header
                    headers:
                      Authorization: Basic aGVsbG86d29ybGQ=
      callbacks:
        CandorResult:
          '{$request.body#/callbackUrl}':
            post:
              summary: Candor Result Callback
              description: Receive notification when a Candor Result has been created.
              requestBody:
                required: true
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/CandorResult'
                    examples:
                      CandorResult:
                        $ref: '#/components/examples/CandorResult'
              responses:
                '2XX':
                  description: Candor Result was received.
                default:
                  description: Any non-success response code will be logged and retried a set number of times
      responses:
        '201':
          description: Callback set
        '400':
          description: Error in Request Body
        default:
          description: Unexpected Error

  /loan/{id}/aus:
    parameters:
    - $ref: 'schemas.yaml#/components/parameters/LoanId'
    post:
      tags:
      - LOS
      operationId: LosProcessAus
      summary: Process AUS comparison
      description: |
        AUS Comparison takes in the most recent DU and LPA XMLs and picks up any D1C (DU) and AIM (LPA) message codes.
        D1C/AIM items provide rep and warranty around income/assets that provides a lift for the lender.
        The lift is that the lender does not need to review these items, the agency has already validated them.

        D1C = Day 1 Certainty aka on day 1, you can be certain of these items

        AIM = Asset and Income Modeler (LPA's version of D1C)
      security:
      - candor-api:
        - candorApi/write:los
      requestBody:
        required: true
        description: Process AUS comparison request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AusComparison'
            examples:
              AusComparisonDUOnly:
                $ref: '#/components/examples/AusComparisonDUOnly'
              AusComparisonBoth:
                $ref: '#/components/examples/AusComparisonBoth'
      responses:
        '200':
          description: Successful response including AUS comparison results
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AusResult'
              examples:
                AusResult:
                  $ref: '#/components/examples/AusResult'
        '400':
          description: An error exists in the request body
        '500':
          description: An error message is returned in the response body

  /loan/{id}/document:
    parameters:
    - $ref: 'schemas.yaml#/components/parameters/LoanId'
    post:
      tags:
      - LOS
      operationId: LosUploadDocument
      summary: Request to upload loan documents
      description: Used by the LOS to upload documents associated with loan `{id}`.
        The request will contain some info about the documents to be uploaded such
        as filename. The results will then contain an upload Url (optionally
        with mandatory headers) that'll be used to upload the document with a PUT
        request.
      security:
      - candor-api:
        - candorApi/write:los
      requestBody:
        required: true
        description: A collection of documents that needs to be uploaded to Candor.
        content:
          application/json:
            schema:
              $ref: 'schemas.yaml#/components/schemas/UploadDocumentRequest'
            examples:
              UploadDocumentRequest:
                $ref: '#/components/examples/UploadDocumentRequest'
      responses:
        '200':
          description: Request body is valid. Individual inspection of an error on each document should be performed. For documents with no error, the LOS would then perform a PUT request at the `upload.url`, using any returned `upload.headers`, and passing the document as the body of the request.
          content:
            application/json:
              schema:
                $ref: 'schemas.yaml#/components/schemas/UploadDocumentResponse'
              examples:
                UploadDocumentResponse:
                  $ref: '#/components/examples/UploadDocumentResponse'
        '400':
          description: Error in Request Body
        default:
          description: Unexpected Error

  /loan/{id}:
    parameters:
    - $ref: 'schemas.yaml#/components/parameters/LoanId'
    post:
      tags:
      - LOS
      operationId: LosProcessLoan
      summary: Process loan with optional documents
      description: Submits Loan data, optionally with documents, to be processed by Candor.
      security:
      - candor-api:
        - candorApi/write:los
      requestBody:
        required: true
        description: Process Loan request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProcessLoan'
            examples:
              ProcessLoanReqNoDocuments:
                $ref: '#/components/examples/ProcessLoanReqNoDocuments'
              ProcessLoanReqWithDocuments:
                $ref: '#/components/examples/ProcessLoanReqWithDocuments'
      responses:
        '200':
          description: Successful response including loan data Candor Results
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CandorResult'
              examples:
                CandorResult:
                  $ref: '#/components/examples/CandorResult'
        '202':
          description: |
            Successful asynchronous response (no body returned).

            The processing of the loan will be done after this response and the caller will be notified of the results when Candor has results to report.

            NOTE: A synchronous request could be converted into an asynchronous request if a Candor Result cannot be returned at this time.
        '400':
          description: An error exists in the request body

components:
  schemas:
    AusComparison:
      type: object
      properties:
        duxml:
          type: string
          description: The content of the DU xml
        lpaxml:
          type: string
          description: The content of the LPA xml

    AusResult:
      type: object
      properties:
        duPiw:
          type: boolean
          description: The DU appraisal waiver.
        duIncome:
          type: boolean
          description: The DU income relief.
        duAssets:
          type: boolean
          description: The DU asset relief.
        lpaAce:
          type: boolean
          description: The LPA appraisal waiver.
        lpaIncome:
          type: boolean
          description: The LPA income relief.
        lpaAssets:
          type: boolean
          description: The LPA asset relief.

    ProcessLoan:
      type: object
      required:
      - loanData
      allOf:
      - $ref: 'schemas.yaml#/components/schemas/ProcessLoanBase'
      properties:
        # DRAFT: possible future structure to accept fraudReport which would
        #   then be pulled and put into loanData before sending to Candor LES
        # fraudReport:
        #   type: object
        #   description: If a fraud report was performed, this data is provided
        #     to Candor in order to pull the fraud report so that it's included
        #     in processing of the loan.
        #   properties:
        #     id:
        #       type: string
        #     ssn:
        #       type: string
        #     name:
        #       type: string
        #     address:
        #       type: string
        loanData:
          type: array
          description: The various loan data associated with the loan. There
            must exist at least the URLA data.
          minItems: 1
          items:
            type: object
            required:
            - data
            - type
            properties:
              data:
                type: string
                description: The content in either xml, json, or base64 format.
              type:
                $ref: 'schemas.yaml#/components/schemas/LoanDataType'
        documentsToProcess:
          type: array
          description: A collection of document Ids previously uploaded to Candor.
          items:
            type: string

    CandorResult:
      allOf:
      - $ref: 'schemas.yaml#/components/schemas/CandorResult'

  examples:
    AusComparisonDUOnly:
      summary: Process AUS comparison request with only DU xml
      value:
        duxml: <xml>...</xml>

    AusComparisonBoth:
      summary: Process AUS comparison request with DU and LPA xml
      value:
        duxml: <xml>...</xml>
        lpaxml: <xml>...</xml>

    AusResult:
      summary: AUS Comparison Result
      value:
        duPiw: true
        duIncome: true
        duAssets: true
        lpaAce: false
        lpaIncome: false
        lpaAssets: false

    CandorResult:
      summary: Candor Result
      value:
        loanId: c8e27489-0381-438f-8148-4b7a2379a64c
        loanName: abc123
        runId: 1
        timestamp: '0001-01-01T00:00:00Z'
        context: 6cea2800-eb9e-4cd5-8136-4dd11dadf388
        insuranceScore: '75'
        insuranceCovered: Pending
        underwritingStatus: Conditional Approval
        occupancy: 10
        identity: 20
        valuation: 30
        liabilities: 40
        assets: 50
        income: null
        conditions:
        - lesId: 4b13424e-3b89-49b5-8ed8-6cc72385f409
          conditionId: 151ce1d9-90e2-4e32-9337-8de6d8124e50
          status: Unfulfilled
          name: Condition Name
          description: Extended descriptive text for this condition
          priorTo: PTD
          owner: Lender
          category: Credit
        results:
        - name: Findings.pdf
          section: Candor - Findings Page
          base64: SGVsbG8gV29ybGQ=
        processedDocuments:
        - parentDocumentId: 3a3b0e08-8b27-4f21-a395-a9b4f3d4548c
          processedDocumentId: ef7db80f-05ee-4757-9ab0-ded649d3becc
          processedCode: 200
          processedMessage: Success
        - parentDocumentId: 7d3ad95c-8479-4359-888b-19ca4456fa12
          processedDocumentId: 8058748d-4425-49c6-8472-628b00cf9d04
          processedCode: 301
          processedMessage: Illegible Document
        - parentDocumentId: edb994ca-3a83-4ee0-a35e-b855fbcced45
          processedDocumentId: 56dbc58b-b8a5-46ce-8874-9402764f9056
          processedCode: 350
          processedMessage: Pages 1,6,13,14 ineligible
        liv:
          income:
          - documentType: W2
            documentData:
            - key: YearFiled
              value: 2020
            - key: EmployerName
              value: Demo Company, INC
            - key: Wages1
              value: 75000.00
            - key: SSIWages3
              value: 76000.00
            - key: SSITax4
              value: 1000.00
            - key: MedicareWages5
              value: 77000.00
            - key: MedicareTax6
              value: 2000.00
          - documentType: Paystub
            documentData:
            - key: PayDate
              value: 8/8/2022
            - key: EmployerName
              value: Demo Company, INC
            - key: PayPeriodBegin
              value: 6/1/2022
            - key: PayPeriodEnd
              value: 8/1/2022
            - key: BaseYTD
              value: 20000.00
            - key: NetAmountPaid
              value: 1000.00

    UploadDocumentRequest:
      summary: Request to upload multiple documents with varying input.
      value:
        documents:
        - id: 371d3620-1c98-4466-9f95-290b7748594d
          filename: HelloWorld.pdf
        - id: 9982324b-577e-4061-94f1-c506182cbe82
        - filename: FooBar.pdf
        - id: f8f1a13e-5cca-4a13-aa50-e1ecc6a93af7

    UploadDocumentResponse:
      summary: Response of multiple document upload request.
      value:
        id: c8e27489-0381-438f-8148-4b7a2379a64c
        documents:
        - id: 371d3620-1c98-4466-9f95-290b7748594d
          upload:
            url: https://bucket.s3.region.amazonws.com/document/path/371d3620-1c98-4466-9f95-290b7748594d.pdf?presigned-data
            headers:
              x-amz-meta-filename: HelloWorld.pdf
        - id: 9982324b-577e-4061-94f1-c506182cbe82
          upload:
            url: https://bucket.s3.region.amazonws.com/document/path/9982324b-577e-4061-94f1-c506182cbe82?presigned-data
        - id: 69f15f0d-ec1c-4a54-9798-9a2bd0803adb
          upload:
            url: https://bucket.s3.region.amazonws.com/document/path/69f15f0d-ec1c-4a54-9798-9a2bd0803adb.pdf?presigned-data
            headers:
              x-amz-meta-filename: FooBar.pdf
        - id: f8f1a13e-5cca-4a13-aa50-e1ecc6a93af7
          error: Document already exists and cannot be overwritten.

    ProcessLoanReqNoDocuments:
      summary: Process loan request without documents
      value:
        context: 6cea2800-eb9e-4cd5-8136-4dd11dadf388
        loanName: abc123
        loanEmails:
        - processor@domain.com
        - underwriter@domain.com
        investors:
          - name: Wells Fargo
            productName: 30 Year Fixed Mortgage
        gse: FannieMae
        # DRAFT: possible future structure to accept fraudReport which would
        #   then be pulled and put into loanData before sending to Candor LES
        # fraudReport:
        #   id: 'abc234'
        #   ssn: '123-23-1234'
        #   name: John Doe
        #   address: 123 Street View
        loanData:
        - data: SGVsbG8gV29ybGQ=
          type: URLA
        - data: <xml>...</xml>
          type: DUXML
        - data: '{ "json": true }'
          type: CREDIT

    ProcessLoanReqWithDocuments:
      summary: Process loan request with documents
      value:
        context: 6cea2800-eb9e-4cd5-8136-4dd11dadf388
        loanName: abc123
        loanEmails:
        - processor@domain.com
        - underwriter@domain.com
        investors:
          - name: Wells Fargo
            productName: 30 Year Fixed Mortgage
        gse: FannieMae
        # DRAFT: possible future structure to accept fraudReport which would
        #   then be pulled and put into loanData before sending to Candor LES
        # fraudReport:
        #   id: 'abc234'
        #   ssn: '123-23-1234'
        #   name: John Doe
        #   address: 123 Street View
        loanData:
        - data: SGVsbG8gV29ybGQ=
          type: URLA
        - data: <xml>...</xml>
          type: DUXML
        - data: '{ "json": true }'
          type: CREDIT
        documentsToProcess:
        - 371d3620-1c98-4466-9f95-290b7748594d
        - 9982324b-577e-4061-94f1-c506182cbe82
        - 69f15f0d-ec1c-4a54-9798-9a2bd0803adb

  securitySchemes:
    candor-api:
      type: oauth2
      description: This will not work in SwaggerUI until CORS is enabled on Cognito
      flows:
        clientCredentials:
          tokenUrl: /token
          scopes:
            candorApi/write:los: Write access to LOS data
